export interface pokemon{
    id?: number,
    name: string,
    level: number,
    experience?: number,
    hp: number,
    attack: number,
    defense: number,
    specialDefense: number,
    specialAttack: number,
    PokemonTypeId1: number,
    pokemonType1Name: string,
    PokemonTypeId2?: number,
    pokemonType2Name?: string,
    speed: number,
    photoUrl: string,
    wildPlaceId?: number,
    attack1Id? : number,
    attack1Name? :string,
    attack1Type? : string,
    attack2Id? : number,
    attack2Name? :string,
    attack2Type? : string,
    attack3Id? : number,
    attack3Name? :string,
    attack3Type? : string,
    attack4Id? : number,
    attack4Name? :string,
    attack4Type? : string,
    isInTeam?: boolean,
}